// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/posts/:postId/subscription": {
    params: {
      postId: string;
    };
  };
  "/api/posts/:postId/reactions": {
    params: {
      postId: string;
    };
  };
  "/api/posts/:postId/comments": {
    params: {
      postId: string;
    };
  };
  "/api/posts/:postId/comments/:commentId": {
    params: {
      postId: string;
      commentId: string;
    };
  };
  "/c/:categorySlug": {
    params: {
      categorySlug: string;
    };
  };
  "/auth/google/callback": {
    params: {};
  };
  "/feeds/:feedId.xml": {
    params: {
      feedId: string;
    };
  };
  "/u/:userEmail": {
    params: {
      userEmail: string;
    };
  };
  "/auth/google": {
    params: {};
  };
  "/p/:postId": {
    params: {
      postId: string;
    };
  };
  "/image-uploads/*": {
    params: {
      "*": string;
    };
  };
  "/p/:postId/edit": {
    params: {
      postId: string;
    };
  };
  "/upload-image": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/auth/basic": {
    params: {};
  };
  "/new-post": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
  "/drafts": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/categories/:categoryId": {
    params: {
      categoryId: string;
    };
  };
  "/admin/categories": {
    params: {};
  };
  "/admin/comments": {
    params: {};
  };
  "/admin/categories/new": {
    params: {};
  };
  "/admin/feeds/:feedId": {
    params: {
      feedId: string;
    };
  };
  "/admin/feeds": {
    params: {};
  };
  "/admin/posts": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/feeds/new": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/401": {
    params: {};
  };
  "/404": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page:
      | "/"
      | "/api/posts/:postId/subscription"
      | "/api/posts/:postId/reactions"
      | "/api/posts/:postId/comments"
      | "/api/posts/:postId/comments/:commentId"
      | "/c/:categorySlug"
      | "/auth/google/callback"
      | "/feeds/:feedId.xml"
      | "/u/:userEmail"
      | "/auth/google"
      | "/p/:postId"
      | "/image-uploads/*"
      | "/p/:postId/edit"
      | "/upload-image"
      | "/auth/logout"
      | "/healthcheck"
      | "/auth/basic"
      | "/new-post"
      | "/settings"
      | "/welcome"
      | "/drafts"
      | "/logout"
      | "/search"
      | "/about"
      | "/admin"
      | "/admin/categories/:categoryId"
      | "/admin/categories"
      | "/admin/comments"
      | "/admin/categories/new"
      | "/admin/feeds/:feedId"
      | "/admin/feeds"
      | "/admin/posts"
      | "/admin/users"
      | "/admin/feeds/new"
      | "/login"
      | "/401"
      | "/404";
  };
  "routes/api.posts.$postId_.subscription.ts": {
    id: "routes/api.posts.$postId_.subscription";
    page: "/api/posts/:postId/subscription";
  };
  "routes/api.posts.$postId_.reactions.ts": {
    id: "routes/api.posts.$postId_.reactions";
    page: "/api/posts/:postId/reactions";
  };
  "routes/api.posts.$postId_.comments.ts": {
    id: "routes/api.posts.$postId_.comments";
    page:
      | "/api/posts/:postId/comments"
      | "/api/posts/:postId/comments/:commentId";
  };
  "routes/api.posts.$postId_.comments.$commentId.ts": {
    id: "routes/api.posts.$postId_.comments.$commentId";
    page: "/api/posts/:postId/comments/:commentId";
  };
  "routes/c.$categorySlug._index.tsx": {
    id: "routes/c.$categorySlug._index";
    page: "/c/:categorySlug";
  };
  "routes/auth.google.callback.tsx": {
    id: "routes/auth.google.callback";
    page: "/auth/google/callback";
  };
  "routes/feeds.$feedId[.]xml.tsx": {
    id: "routes/feeds.$feedId[.]xml";
    page: "/feeds/:feedId.xml";
  };
  "routes/u.$userEmail._index.tsx": {
    id: "routes/u.$userEmail._index";
    page: "/u/:userEmail";
  };
  "routes/auth.google._index.tsx": {
    id: "routes/auth.google._index";
    page: "/auth/google";
  };
  "routes/p.$postId._index.tsx": {
    id: "routes/p.$postId._index";
    page: "/p/:postId";
  };
  "routes/image-uploads.$.tsx": {
    id: "routes/image-uploads.$";
    page: "/image-uploads/*";
  };
  "routes/p.$postId_.edit.tsx": {
    id: "routes/p.$postId_.edit";
    page: "/p/:postId/edit";
  };
  "routes/upload-image.tsx": {
    id: "routes/upload-image";
    page: "/upload-image";
  };
  "routes/auth.logout.tsx": {
    id: "routes/auth.logout";
    page: "/auth/logout";
  };
  "routes/healthcheck.tsx": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
  "routes/auth.basic.tsx": {
    id: "routes/auth.basic";
    page: "/auth/basic";
  };
  "routes/new-post.tsx": {
    id: "routes/new-post";
    page: "/new-post";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/welcome.tsx": {
    id: "routes/welcome";
    page: "/welcome";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/drafts.tsx": {
    id: "routes/drafts";
    page: "/drafts";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page:
      | "/admin"
      | "/admin/categories/:categoryId"
      | "/admin/categories"
      | "/admin/comments"
      | "/admin/categories/new"
      | "/admin/feeds/:feedId"
      | "/admin/feeds"
      | "/admin/posts"
      | "/admin/users"
      | "/admin/feeds/new";
  };
  "routes/admin.categories.$categoryId.tsx": {
    id: "routes/admin.categories.$categoryId";
    page: "/admin/categories/:categoryId";
  };
  "routes/admin.categories._index.tsx": {
    id: "routes/admin.categories._index";
    page: "/admin/categories";
  };
  "routes/admin.comments._index.tsx": {
    id: "routes/admin.comments._index";
    page: "/admin/comments";
  };
  "routes/admin.categories.new.tsx": {
    id: "routes/admin.categories.new";
    page: "/admin/categories/new";
  };
  "routes/admin.feeds.$feedId.tsx": {
    id: "routes/admin.feeds.$feedId";
    page: "/admin/feeds/:feedId";
  };
  "routes/admin.feeds._index.tsx": {
    id: "routes/admin.feeds._index";
    page: "/admin/feeds";
  };
  "routes/admin.posts._index.tsx": {
    id: "routes/admin.posts._index";
    page: "/admin/posts";
  };
  "routes/admin.users._index.tsx": {
    id: "routes/admin.users._index";
    page: "/admin/users";
  };
  "routes/admin.feeds.new.tsx": {
    id: "routes/admin.feeds.new";
    page: "/admin/feeds/new";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/401.tsx": {
    id: "routes/401";
    page: "/401";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/404";
  };
};

type RouteModules = {
  root: typeof import("./app/root.tsx");
  "routes/api.posts.$postId_.subscription": typeof import("./app/routes/api.posts.$postId_.subscription.ts");
  "routes/api.posts.$postId_.reactions": typeof import("./app/routes/api.posts.$postId_.reactions.ts");
  "routes/api.posts.$postId_.comments": typeof import("./app/routes/api.posts.$postId_.comments.ts");
  "routes/api.posts.$postId_.comments.$commentId": typeof import("./app/routes/api.posts.$postId_.comments.$commentId.ts");
  "routes/c.$categorySlug._index": typeof import("./app/routes/c.$categorySlug._index.tsx");
  "routes/auth.google.callback": typeof import("./app/routes/auth.google.callback.tsx");
  "routes/feeds.$feedId[.]xml": typeof import("./app/routes/feeds.$feedId[.]xml.tsx");
  "routes/u.$userEmail._index": typeof import("./app/routes/u.$userEmail._index.tsx");
  "routes/auth.google._index": typeof import("./app/routes/auth.google._index.tsx");
  "routes/p.$postId._index": typeof import("./app/routes/p.$postId._index.tsx");
  "routes/image-uploads.$": typeof import("./app/routes/image-uploads.$.tsx");
  "routes/p.$postId_.edit": typeof import("./app/routes/p.$postId_.edit.tsx");
  "routes/upload-image": typeof import("./app/routes/upload-image.tsx");
  "routes/auth.logout": typeof import("./app/routes/auth.logout.tsx");
  "routes/healthcheck": typeof import("./app/routes/healthcheck.tsx");
  "routes/auth.basic": typeof import("./app/routes/auth.basic.tsx");
  "routes/new-post": typeof import("./app/routes/new-post.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/welcome": typeof import("./app/routes/welcome.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/drafts": typeof import("./app/routes/drafts.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin.categories.$categoryId": typeof import("./app/routes/admin.categories.$categoryId.tsx");
  "routes/admin.categories._index": typeof import("./app/routes/admin.categories._index.tsx");
  "routes/admin.comments._index": typeof import("./app/routes/admin.comments._index.tsx");
  "routes/admin.categories.new": typeof import("./app/routes/admin.categories.new.tsx");
  "routes/admin.feeds.$feedId": typeof import("./app/routes/admin.feeds.$feedId.tsx");
  "routes/admin.feeds._index": typeof import("./app/routes/admin.feeds._index.tsx");
  "routes/admin.posts._index": typeof import("./app/routes/admin.posts._index.tsx");
  "routes/admin.users._index": typeof import("./app/routes/admin.users._index.tsx");
  "routes/admin.feeds.new": typeof import("./app/routes/admin.feeds.new.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/401": typeof import("./app/routes/401.tsx");
  "routes/404": typeof import("./app/routes/404.tsx");
};
