// @ts-nocheck
import sharp from "sharp";
import { expectRequiresUser } from "~/lib/test/expects";
import { buildRequest } from "~/lib/test/request";
import { action } from "./upload-image";

// Real image bytes generated by sharp on demand — the upload pipeline now
// validates buffers via sharp, so toy / fake byte sequences (`Buffer.from("fake-png")`,
// truncated JPEGs) are rejected as 400. Generating real pixels here mirrors
// what a browser would actually POST.
const makeImage = (format: "jpeg" | "png") =>
  sharp({
    create: { width: 8, height: 8, channels: 3, background: { r: 200, g: 50, b: 50 } },
  })
    [format]()
    .toBuffer();

const buildUploadRequest = async (file: File) => {
  const formData = new FormData();
  formData.append("file", file);
  return buildRequest(
    "http://localhost/upload-image",
    { method: "POST", body: formData },
    { user: DefaultFixtures.DEFAULT_USER },
  );
};

describe("POST /upload-image", () => {
  it("requires user", async () => {
    await expectRequiresUser(
      action({
        request: await buildRequest(`http://localhost/upload-image`, {
          method: "POST",
        }),
        params: {},
        context: {},
      }),
    );
  });

  it("rejects SVG uploads", async () => {
    const svg = new File(["<svg><script>alert(1)</script></svg>"], "evil.svg", {
      type: "image/svg+xml",
    });
    const request = await buildUploadRequest(svg);
    const response = await action({ request, params: {}, context: {} });
    expect(response.status).toBe(400);
    const body = await response.json();
    expect(body.error).toMatch(/JPEG|PNG|GIF|WebP/i);
  });

  it("rejects HTML uploads disguised as images", async () => {
    const html = new File(["<html><script>alert(1)</script></html>"], "page.html", {
      type: "text/html",
    });
    const request = await buildUploadRequest(html);
    const response = await action({ request, params: {}, context: {} });
    expect(response.status).toBe(400);
  });

  it("accepts JPEG uploads", async () => {
    const jpeg = new File([await makeImage("jpeg")], "photo.jpg", { type: "image/jpeg" });
    const request = await buildUploadRequest(jpeg);
    const result = await action({ request, params: {}, context: {} });
    // Real JPEG bytes — the action returns a plain object on success.
    expect(result).not.toBeInstanceOf(Response);
    expect(result.url).toMatch(/\/image-uploads\//);
  });

  it("rejects buffers that don't actually decode as an image with 400", async () => {
    // MIME type says PNG but the bytes are nonsense — sharp catches this
    // even though the claimed Content-Type passed the allowlist.
    const bogus = new File([Buffer.from("not actually a png")], "fake.png", { type: "image/png" });
    const request = await buildUploadRequest(bogus);
    const response = await action({ request, params: {}, context: {} });
    expect(response.status).toBe(400);
    const body = await response.json();
    expect(body.error).toMatch(/invalid/i);
  });

  it("stores file without original filename in URL", async () => {
    // Uploaded as PNG. After optimization the stored object is a WebP, so the
    // proxy URL ends in `.webp` regardless of the source extension.
    const png = new File([await makeImage("png")], "evil.svg.png", { type: "image/png" });
    const request = await buildUploadRequest(png);
    const result = await action({ request, params: {}, context: {} });
    expect(result).not.toBeInstanceOf(Response);
    expect(result.url).toMatch(/\/image-uploads\/[^/]+\/[a-z0-9]+\.webp$/);
    expect(result.url).not.toContain("evil");
  });
});
